language:
  - cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y cmake valgrind libboost-dev libboost-regex-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
after_script:
  - valgrind --leak-check=full --show-reachable=yes --error-exitcode=1 ./tests/application/application
  - valgrind --leak-check=full --show-reachable=yes --error-exitcode=1 ./tests/basic/basic
  - valgrind --leak-check=full --show-reachable=yes --error-exitcode=1 ./tests/request/request